# WORKING ON NUMPY ARRAYS.

# ARRAY() METHOD

In [7]:
import numpy as np
arr = np.array([[9,8,7], [6,5,4]]) # Creat a 2-D Array
print(arr) 

[[9 8 7]
 [6 5 4]]


# ARRAY ATTRIBUTES

In [11]:
print(arr.size) # Displays the number of elements in a array

6


In [13]:
print(arr.shape) # Display the rows and columns

(2, 3)


In [15]:
print(arr.ndim) # Displays the dimension of array

2


# RESHAPE METHOD

In [19]:
arr = np.array([9,8,7,6,5,4])
print("Original array:", arr)
print("Original shape:", arr.shape)

Original array: [9 8 7 6 5 4]
Original shape: (6,)


In [21]:
# Reshape to a 2D array (2 rows, 3 columns)
reshaped_arr = arr.reshape(2, 3) # Reshape a 1-D array to 2-D array
print(reshaped_arr)
print("New shape:", reshaped_arr.shape)

[[9 8 7]
 [6 5 4]]
New shape: (2, 3)


# ARRANGE METHOD

In [25]:
import numpy as np
def numpysum(n):
  a = np.arange(n) ** 2  # creates an array [0,1,..n-1] and element-wise sqauring
  b = np.arange(n) ** 3
  c = a + b              # element wise adding - NO LOOP Overhead, hence Memory Efficient
  return c

numpysum(10)

array([  0,   2,  12,  36,  80, 150, 252, 392, 576, 810])

# ARRAY CREATION FUNCTION

In [29]:
import numpy as np
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [31]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [39]:
np.arange(2, 3, 0.05)  # step value is 0.05

array([2.  , 2.05, 2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 ,
       2.55, 2.6 , 2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95])

# ARRAY METHOD

In [43]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [45]:
B = np.array([[1, 2], [3, 4]])
print(B)

[[1 2]
 [3 4]]


In [47]:
#In general, any array object is called an ndarray in NumPy.
C = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(C)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# DTYPE ATTRIBUTE

In [51]:
import numpy as np
np.array([127, 128, 129], dtype=np.int32)

array([127, 128, 129])

In [53]:
import numpy as np
np.array([127, 128, 129], dtype=np.int8)

C:\Users\gokul\AppData\Local\Temp\ipykernel_3568\1903986189.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([127, 128, 129], dtype=np.int8)
C:\Users\gokul\AppData\Local\Temp\ipykernel_3568\1903986189.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([127, 128, 129], dtype=np.int8)


array([ 127, -128, -127], dtype=int8)

# LINSPACE METHOD

In [57]:
# The interval is divided into 5 equal steps (because 6 points mean 5 intervals).
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

# EYE METHOD IN NUMPY

In [61]:
#properties of special matrices represented as 2D arrays.
np.eye(4) # Identity matrice of 3X3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [63]:
np.eye(4,6)   # Identity matrice of 4X6

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [65]:

np.eye(4,6, k=-4) #optional k argument
# When k is negative (e.g., k=-4), the diagonal shifts below the main diagonal
# when k is positive (e.g., k=1), the diagonal shifts above the main diagonal. 

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [67]:
np.eye(3, 5, k=2) # Positive k argument

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# DIAG METHOD

In [71]:
# It returns an array containing the elements of the specified diagonal. 
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [73]:
# To hold this upper diagonal, NumPy creates a (n + k) × (n + k) square matrix, where n is the length of the input array.
# So for [1, 2, 3]: Length = 3, k = 1, Matrix shape = 4 × 4
# Diagonal values are placed at positions: (0,1), (1,2), (2,3)
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [75]:
a = np.array([[1, 2], [3, 4]])
np.diag(a)

array([1, 4])

# VANDERMONDE MATRIX

In [79]:
# N = 2 → two columns: x**1, x**0
np.vander(np.linspace(0, 2, 5), 2)

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [84]:
#np.vander(x, N) creates a Vandermonde matrix from a 1D input array x.

# [[x₁**(N-1), x₁**(N-2), ..., x₁**0],
#  [x₂**(N-1), x₂**(N-2), ..., x₂**0],
#  ...
#  [xₙ**(N-1), xₙ**(N-2), ..., xₙ**0]]

# So each row is a decreasing power of an element from x.

In [86]:
np.vander([1, 2, 3, 4], 2) # creates 4X2 matrix

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

In [88]:
np.vander((1, 2, 3, 4), 4) # creates 4X4 matrix

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [90]:
np.vander((1,2,3,4),3) # Each row is [x**2, x, 1] for each x in the input.

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

# ONES METHOD

In [94]:
arr1 = np.ones(5)  # shape=5 (1D), default dtype=float
print("1D Array of Ones:", arr1)

1D Array of Ones: [1. 1. 1. 1. 1.]


In [96]:
arr2 = np.ones((3, 4))  # shape=(3,4) means 3x4 matrix
print("\n2D Array (3x4) of Ones:\n", arr2)


2D Array (3x4) of Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [98]:
arr3 = np.ones((2, 3), dtype=int)  # shape=(2,3), dtype=int
print("\n2D Integer Array (2x3) of Ones:\n", arr3)


2D Integer Array (2x3) of Ones:
 [[1 1 1]
 [1 1 1]]


In [100]:
arr4 = np.ones((2, 2, 3))  # shape=(2,2,3) means 3D array (2 blocks, 2 rows, 3 columns)
print("\n3D Array of Ones:\n", arr4)


3D Array of Ones:
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [102]:
arr5 = np.ones((3, 3), dtype=bool)
print("\nBoolean Array (3x3) of Ones (True values):\n", arr5)


Boolean Array (3x3) of Ones (True values):
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# ZEROS METHOD

In [106]:
arr1 = np.zeros(5)  # shape=5 (1D), default dtype=float
print("1D Array of Zeros:", arr1)

1D Array of Zeros: [0. 0. 0. 0. 0.]


In [108]:
arr2 = np.zeros((3, 4))  # shape=(3,4) means 3x4 matrix
print("\n2D Array (3x4) of Zeros:\n", arr2)


2D Array (3x4) of Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [110]:
arr3 = np.zeros((2, 3), dtype=int)  # shape=(2,3), dtype=int
print("\n2D Integer Array (2x3) of Zeros:\n", arr3)


2D Integer Array (2x3) of Zeros:
 [[0 0 0]
 [0 0 0]]


In [112]:
arr4 = np.zeros((2, 2, 3))  # shape=(2,2,3) means 3D array (2 blocks, 2 rows, 3 columns)
print("\n3D Array of Zeros:\n", arr4)


3D Array of Zeros:
 [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


# INDICES METHOD

In [116]:
indices_2d = np.indices((3, 3))  # shape=(3,3) means 3 rows and 3 columns
print("Indices for a 3x3 grid:\n", indices_2d)

Indices for a 3x3 grid:
 [[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


In [118]:
print("\nRow indices (first array):\n", indices_2d[0])


Row indices (first array):
 [[0 0 0]
 [1 1 1]
 [2 2 2]]


In [120]:
print("\nColumn indices (second array):\n", indices_2d[1])


Column indices (second array):
 [[0 1 2]
 [0 1 2]
 [0 1 2]]


In [122]:
indices_2x4 = np.indices((2, 4))
print("\nIndices for a 2x4 grid:\n", indices_2x4)


Indices for a 2x4 grid:
 [[[0 0 0 0]
  [1 1 1 1]]

 [[0 1 2 3]
  [0 1 2 3]]]


In [124]:
print("\nRow indices:\n", indices_2x4[0])


Row indices:
 [[0 0 0 0]
 [1 1 1 1]]


In [126]:
print("\nColumn indices:\n", indices_2x4[1])


Column indices:
 [[0 1 2 3]
 [0 1 2 3]]


# RANDOM METHOD

In [130]:
random_float = np.random.random()
print("Random Float (0 to 1):", random_float)

Random Float (0 to 1): 0.7763165821287219


In [132]:
random_array = np.random.random(5)
print("\n1D Array of Random Floats:", random_array)


1D Array of Random Floats: [0.34503207 0.1488537  0.11296723 0.18727407 0.69255197]


In [134]:
random_matrix = np.random.random((3, 3))
print("\n2D Array (3x3) of Random Floats:\n", random_matrix)


2D Array (3x3) of Random Floats:
 [[0.49132102 0.18426833 0.75479059]
 [0.43977014 0.32961005 0.57570241]
 [0.68725006 0.93640377 0.67416482]]


In [136]:
random_integers = np.random.randint(10, 50, size=5)
print("\nRandom Integers between 10 and 50:", random_integers)


Random Integers between 10 and 50: [16 32 47 43 40]


In [138]:
random_normal = np.random.randn(4)
print("\nRandom Numbers from Normal Distribution:", random_normal)


Random Numbers from Normal Distribution: [ 0.07756878 -0.19573156 -1.21399451  0.87726512]


# SLICING AND INDEXING IN ARRAYS

In [146]:
arr1d = np.array([50,60,70,80,90,100])
print("1D Array:", arr1d)

1D Array: [ 50  60  70  80  90 100]


In [148]:
print("\nIndexing on 1D Array:")
print("Element at index 0:", arr1d[0])   # First element
print("Element at index -1:", arr1d[-1]) # Last element


Indexing on 1D Array:
Element at index 0: 50
Element at index -1: 100


In [150]:
print("\nSlicing on 1D Array:")
print("Elements from index 1 to 4:", arr1d[1:5])  # From index 1 up to 4
print("Every second element:", arr1d[::2])        # Step of 2
print("Reverse array:", arr1d[::-1])


Slicing on 1D Array:
Elements from index 1 to 4: [60 70 80 90]
Every second element: [50 70 90]
Reverse array: [100  90  80  70  60  50]


In [152]:
#Create a 2D array (3x4 matrix)
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
print("\n2D Array:\n", arr2d)


2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [154]:
print("\nIndexing on 2D Array:")
print("Element at row 1, column 2:", arr2d[1, 2])   # 7 (row=1, col=2)
print("First row:", arr2d[0])                      # Whole first row
print("First column:", arr2d[:, 0])


Indexing on 2D Array:
Element at row 1, column 2: 7
First row: [1 2 3 4]
First column: [1 5 9]
